### ISSUE TITLE
The Twitter4A consumer thread never stops

### ISSUE THREAD

**Issue by Tristan971** [takke/twitter4a#3]
I'm immensely happy to see that someone took upon themselves to actually fork Twitter4J before it would just have died so thank you for that.

Now a long-standing issue I've had with it is the lack of documentation regarding how to properly stop a user stream. Right now unless I forcibly shutdown the whole VM via `Runtime.getRuntime().halt(0)`, one of the Twitter4A streaming threads stay running forever.

I am 100% sure that this call is executed upon close request of the application, yet it's not sufficient:
![2018-07-24 05_54_30-task switching](https://user-images.githubusercontent.com/875533/43116277-2019236e-8f07-11e8-86b0-0b20495fd5ef.png)

The thread I identified it to be the one from `TwitterStreamConsumer` whose close method should be called during `TwitterStream#close` call but unfortunately is not because the TwitterStream one is never called which I guess is due to synchronization issues.
![2018-07-24 06_03_04-task switching](https://user-images.githubusercontent.com/875533/43116307-45837c58-8f07-11e8-8b97-ae83458def9f.png)

![2018-07-24 06_02_47-task switching](https://user-images.githubusercontent.com/875533/43116306-4275770a-8f07-11e8-830a-206912ce8e97.png)

I don't know if I'm doing things wrong or if it is a real issue in the end but at least there is no documentation and I think it's not super intuitive I guess 🤔

**Comment by Tristan971** [comment]
So I have narrowed it down to bad threading model on my side but it still takes about 25 seconds to stop the listener which is a fairly long time for this I believe? Any idea why it would take so long? Waiting on some TCP timeout?

**Comment by takke** [comment]
I've been using similar code for Android application for quite a while.

I call ```shutdown()``` only.

It seems there is no need to call ```cleanUp()``` at least because ```shutdown()``` calls ```cleanUp()```.

In any case, streaming can not be used in two weeks, so I do not think we need to fix it.

**Comment by Tristan971** [comment]
Yeah it's true that there's no point fixing it right now anymore
